# Generated by Django 4.2.7 on 2023-11-02 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="number_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name="UserAddress",
        ),
    ]
