# Generated by Django 4.2.7 on 2023-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_orderitems_created_at_orderitems_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
