# Generated by Django 4.2.7 on 2023-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_fooditem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="medai/restraunt/"),
        ),
    ]
