# Generated by Django 4.2.7 on 2023-11-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_restaurant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("owner", "OWNER"), ("customer", "CUSTOMER")],
                max_length=255,
                null=True,
            ),
        ),
    ]
