# Generated by Django 4.1.7 on 2023-11-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_orderitems_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
